name: Terraform Deploy

on:
  push:
    branches:
      - dev
      - main

env:
  AWS_REGION: us-east-1
  STATE_BUCKET_NAME: sanjai-dev-tf-state
  DYNAMODB_TABLE_NAME: sanjai-dev-tf-stat
  WORKSPACE_KEY_PREFIX: s3-frontend

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Set environment from branch
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "env=qa" >> "$GITHUB_OUTPUT"
          else
            echo "env=dev" >> "$GITHUB_OUTPUT"
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.STATE_BUCKET_NAME }}" \
            -backend-config="key=${{ steps.env.outputs.env }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.DYNAMODB_TABLE_NAME }}" \
            -backend-config="workspace_key_prefix=${{ env.WORKSPACE_KEY_PREFIX }}"

      - name: Select or Create Workspace
        run: |
          terraform workspace select ${{ steps.env.outputs.env }} || terraform workspace new ${{ steps.env.outputs.env }}

      - name: Terraform Plan
        run: terraform plan -var-file=vars_${{ steps.env.outputs.env }}.tfvars -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: terraform apply -input=false tfplan
