name: Terraform Promotion Pipeline

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials (Account A)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::853973692277:role/sanjai-oidc-2
          aws-region: ${{ vars.AWS_REGION_ACCOUNT_A }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.STATE_BUCKET_NAME_A }}" \
            -backend-config="key=dev/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION_ACCOUNT_A }}" \
            -backend-config="dynamodb_table=${{ vars.DYNAMODB_TABLE_NAME_A }}" \
            -backend-config="workspace_key_prefix=${{ vars.WORKSPACE_KEY_PREFIX }}"

      - name: Select or Create Workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Plan
        run: terraform plan -var-file=vars_dev.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan

  qa:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment:
      name: qa
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials (Account A)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::853973692277:role/sanjai-oidc-2
          aws-region: ${{ vars.AWS_REGION_ACCOUNT_A }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.STATE_BUCKET_NAME_A }}" \
            -backend-config="key=qa/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION_ACCOUNT_A }}" \
            -backend-config="dynamodb_table=${{ vars.DYNAMODB_TABLE_NAME_A }}" \
            -backend-config="workspace_key_prefix=${{ vars.WORKSPACE_KEY_PREFIX }}"

      - name: Select or Create Workspace
        run: terraform workspace select qa || terraform workspace new qa

      - name: Terraform Plan
        run: terraform plan -var-file=vars_qa.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan

  preprod:
    needs: qa
    runs-on: ubuntu-latest
    environment:
      name: preprod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials (Account B)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::615719431409:role/sanjai-oidc
          aws-region: ${{ vars.AWS_REGION_ACCOUNT_B }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.STATE_BUCKET_NAME_B }}" \
            -backend-config="key=preprod/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION_ACCOUNT_B }}" \
            -backend-config="dynamodb_table=${{ vars.DYNAMODB_TABLE_NAME_B }}" \
            -backend-config="workspace_key_prefix=${{ vars.WORKSPACE_KEY_PREFIX }}"

      - name: Select or Create Workspace
        run: terraform workspace select preprod || terraform workspace new preprod

      - name: Terraform Plan
        run: terraform plan -var-file=vars_preprod.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan

  prod:
    needs: preprod
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials (Account B)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::615719431409:role/sanjai-oidc
          aws-region: ${{ vars.AWS_REGION_ACCOUNT_B }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.STATE_BUCKET_NAME_B }}" \
            -backend-config="key=prod/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION_ACCOUNT_B }}" \
            -backend-config="dynamodb_table=${{ vars.DYNAMODB_TABLE_NAME_B }}" \
            -backend-config="workspace_key_prefix=${{ vars.WORKSPACE_KEY_PREFIX }}"

      - name: Select or Create Workspace
        run: terraform workspace select prod || terraform workspace new prod

      - name: Terraform Plan
        run: terraform plan -var-file=vars_prod.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
