name: Terraform Destroy QA

on:
  workflow_dispatch: # Manual trigger from GitHub UI.

jobs:
  destroy_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::853973692277:role/sanjai-oidc-2
          aws-region: ${{ vars.AWS_REGION_ACCOUNT_A }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.STATE_BUCKET_NAME_A }}" \
            -backend-config="key=qa/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION_ACCOUNT_A }}" \
            -backend-config="dynamodb_table=${{ vars.DYNAMODB_TABLE_NAME_A }}" \
            -backend-config="workspace_key_prefix=${{ vars.WORKSPACE_KEY_PREFIX }}"

      - name: Select Workspace
        run: terraform workspace select qa

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=vars_qa.tfvars

      - name: Delete Workspace
        run: terraform workspace delete qa


